package com.globalbettingexchange.externalapi;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-01-22T16:23:34.094Z
 * Generated source version: 3.3.5
 *
 */
@WebServiceClient(name = "ReadOnlyService",
                  wsdlLocation = "http://api.betdaq.com/v2.0/API.wsdl",
                  targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
public class ReadOnlyService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.GlobalBettingExchange.com/ExternalAPI/", "ReadOnlyService");
    public final static QName ReadOnlyService = new QName("http://www.GlobalBettingExchange.com/ExternalAPI/", "ReadOnlyService");
    static {
        URL url = null;
        try {
            url = new URL("http://api.betdaq.com/v2.0/API.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ReadOnlyService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://api.betdaq.com/v2.0/API.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ReadOnlyService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReadOnlyService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReadOnlyService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ReadOnlyService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ReadOnlyService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ReadOnlyService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ReadOnlyService
     */
    @WebEndpoint(name = "ReadOnlyService")
    public ReadOnlyService getReadOnlyService() {
        return super.getPort(ReadOnlyService, ReadOnlyService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReadOnlyService
     */
    @WebEndpoint(name = "ReadOnlyService")
    public ReadOnlyService getReadOnlyService(WebServiceFeature... features) {
        return super.getPort(ReadOnlyService, ReadOnlyService.class, features);
    }

}
