package com.globalbettingexchange.externalapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-01-22T16:23:34.013Z
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", name = "ReadOnlyService")
@XmlSeeAlso({ObjectFactory.class})
public interface ReadOnlyService {

    /**
     * Returns the maximum selection sequence number.
     */
    @WebMethod(operationName = "GetCurrentSelectionSequenceNumber", action = "http://www.GlobalBettingExchange.com/ExternalAPI/GetCurrentSelectionSequenceNumber")
    @RequestWrapper(localName = "GetCurrentSelectionSequenceNumber", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetCurrentSelectionSequenceNumber")
    @ResponseWrapper(localName = "GetCurrentSelectionSequenceNumberResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetCurrentSelectionSequenceNumberResponse")
    @WebResult(name = "GetCurrentSelectionSequenceNumberResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public GetCurrentSelectionSequenceNumberResponse2 getCurrentSelectionSequenceNumber(

            @WebParam(name = "getCurrentSelectionSequenceNumberRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    GetCurrentSelectionSequenceNumberRequest getCurrentSelectionSequenceNumberRequest
    );

    /**
     * Returns the prices for the specified markets.
     */
    @WebMethod(operationName = "GetPrices", action = "http://www.GlobalBettingExchange.com/ExternalAPI/GetPrices")
    @RequestWrapper(localName = "GetPrices", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetPrices")
    @ResponseWrapper(localName = "GetPricesResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetPricesResponse")
    @WebResult(name = "GetPricesResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public GetPricesResponse2 getPrices(

            @WebParam(name = "getPricesRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    GetPricesRequest getPricesRequest
    );

    /**
     * Returns the tree of events and markets.
     */
    @WebMethod(operationName = "GetEventSubTreeNoSelections", action = "http://www.GlobalBettingExchange.com/ExternalAPI/GetEventSubTreeNoSelections")
    @RequestWrapper(localName = "GetEventSubTreeNoSelections", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetEventSubTreeNoSelections")
    @ResponseWrapper(localName = "GetEventSubTreeNoSelectionsResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetEventSubTreeNoSelectionsResponse")
    @WebResult(name = "GetEventSubTreeNoSelectionsResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public GetEventSubTreeNoSelectionsResponse2 getEventSubTreeNoSelections(

            @WebParam(name = "getEventSubTreeNoSelectionsRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    GetEventSubTreeNoSelectionsRequest getEventSubTreeNoSelectionsRequest
    );

    /**
     * Returns the tree of events and markets.
     */
    @WebMethod(operationName = "GetMarketInformation", action = "http://www.GlobalBettingExchange.com/ExternalAPI/GetMarketInformation")
    @RequestWrapper(localName = "GetMarketInformation", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetMarketInformation")
    @ResponseWrapper(localName = "GetMarketInformationResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetMarketInformationResponse")
    @WebResult(name = "GetMarketInformationResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public GetMarketInformationResponse2 getMarketInformation(

            @WebParam(name = "getMarketInformationRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    GetMarketInformationRequest getMarketInformationRequest
    );

    /**
     * Returns history of withdrawals for a given market.
     */
    @WebMethod(operationName = "ListMarketWithdrawalHistory", action = "http://www.GlobalBettingExchange.com/ExternalAPI/ListMarketWithdrawalHistory")
    @RequestWrapper(localName = "ListMarketWithdrawalHistory", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListMarketWithdrawalHistory")
    @ResponseWrapper(localName = "ListMarketWithdrawalHistoryResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListMarketWithdrawalHistoryResponse")
    @WebResult(name = "ListMarketWithdrawalHistoryResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public ListMarketWithdrawalHistoryResponse2 listMarketWithdrawalHistory(

            @WebParam(name = "listMarketWithdrawalHistoryRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    ListMarketWithdrawalHistoryRequest listMarketWithdrawalHistoryRequest
    );

    /**
     * Returns the current odds ladder in requested price format."
     */
    @WebMethod(operationName = "GetOddsLadder", action = "http://www.GlobalBettingExchange.com/ExternalAPI/GetOddsLadder")
    @RequestWrapper(localName = "GetOddsLadder", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetOddsLadder")
    @ResponseWrapper(localName = "GetOddsLadderResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetOddsLadderResponse")
    @WebResult(name = "GetOddsLadderResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public GetOddsLadderResponse2 getOddsLadder(

            @WebParam(name = "getOddsLadderRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    GetOddsLadderRequest getOddsLadderRequest
    );

    /**
     * Returns tagged value information for Event Classifiers, Markets And Selections.
     */
    @WebMethod(operationName = "ListTaggedValues", action = "http://www.GlobalBettingExchange.com/ExternalAPI/ListTaggedValues")
    @RequestWrapper(localName = "ListTaggedValues", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListTaggedValues")
    @ResponseWrapper(localName = "ListTaggedValuesResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListTaggedValuesResponse")
    @WebResult(name = "ListTaggedValuesResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public ListTaggedValuesResponse2 listTaggedValues(

            @WebParam(name = "listTaggedValuesRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    ListTaggedValuesRequest listTaggedValuesRequest
    );

    /**
     * Returns the tree of events and markets.
     */
    @WebMethod(operationName = "GetEventSubTreeWithSelections", action = "http://www.GlobalBettingExchange.com/ExternalAPI/GetEventSubTreeWithSelections")
    @RequestWrapper(localName = "GetEventSubTreeWithSelections", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetEventSubTreeWithSelections")
    @ResponseWrapper(localName = "GetEventSubTreeWithSelectionsResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetEventSubTreeWithSelectionsResponse")
    @WebResult(name = "GetEventSubTreeWithSelectionsResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public GetEventSubTreeWithSelectionsResponse2 getEventSubTreeWithSelections(

            @WebParam(name = "getEventSubTreeWithSelectionsRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    GetEventSubTreeWithSelectionsRequest getEventSubTreeWithSelectionsRequest
    );

    /**
     * Returns the history of trades on the selection(s) specified.
     */
    @WebMethod(operationName = "ListSelectionTrades", action = "http://www.GlobalBettingExchange.com/ExternalAPI/ListSelectionTrades")
    @RequestWrapper(localName = "ListSelectionTrades", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListSelectionTrades")
    @ResponseWrapper(localName = "ListSelectionTradesResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListSelectionTradesResponse")
    @WebResult(name = "ListSelectionTradesResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public ListSelectionTradesResponse2 listSelectionTrades(

            @WebParam(name = "listSelectionTradesRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    ListSelectionTradesRequest listSelectionTradesRequest
    );

    /**
     * Returns the set of top level events that are currently active.
     */
    @WebMethod(operationName = "ListTopLevelEvents", action = "http://www.GlobalBettingExchange.com/ExternalAPI/ListTopLevelEvents")
    @RequestWrapper(localName = "ListTopLevelEvents", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListTopLevelEvents")
    @ResponseWrapper(localName = "ListTopLevelEventsResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListTopLevelEventsResponse")
    @WebResult(name = "ListTopLevelEventsResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public ListTopLevelEventsResponse2 listTopLevelEvents(

            @WebParam(name = "listTopLevelEventsRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    ListTopLevelEventsRequest listTopLevelEventsRequest
    );

    /**
     * Returns information defining which markets are enabled for starting-price orders.
     */
    @WebMethod(operationName = "GetSPEnabledMarketsInformation", action = "http://www.GlobalBettingExchange.com/ExternalAPI/GetSPEnabledMarketsInformation")
    @RequestWrapper(localName = "GetSPEnabledMarketsInformation", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetSPEnabledMarketsInformation")
    @ResponseWrapper(localName = "GetSPEnabledMarketsInformationResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetSPEnabledMarketsInformationResponse")
    @WebResult(name = "GetSPEnabledMarketsInformationResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public GetSPEnabledMarketsInformationResponse2 getSPEnabledMarketsInformation(

            @WebParam(name = "GetSPEnabledMarketsInformationRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    GetSPEnabledMarketsInformationRequest getSPEnabledMarketsInformationRequest
    );

    /**
     * Returns the selections with a sequence number greater than the sequence number provided.
     */
    @WebMethod(operationName = "ListSelectionsChangedSince", action = "http://www.GlobalBettingExchange.com/ExternalAPI/ListSelectionsChangedSince")
    @RequestWrapper(localName = "ListSelectionsChangedSince", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListSelectionsChangedSince")
    @ResponseWrapper(localName = "ListSelectionsChangedSinceResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListSelectionsChangedSinceResponse")
    @WebResult(name = "ListSelectionsChangedSinceResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public ListSelectionsChangedSinceResponse2 listSelectionsChangedSince(

            @WebParam(name = "listSelectionsChangedSinceRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    ListSelectionsChangedSinceRequest listSelectionsChangedSinceRequest
    );
}
