package com.globalbettingexchange.externalapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-01-22T16:23:34.073Z
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", name = "SecureService")
@XmlSeeAlso({ObjectFactory.class})
public interface SecureService {

    /**
     * Cancels one or more orders on the exchange.
     */
    @WebMethod(operationName = "CancelOrders", action = "http://www.GlobalBettingExchange.com/ExternalAPI/CancelOrders")
    @RequestWrapper(localName = "CancelOrders", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.CancelOrders")
    @ResponseWrapper(localName = "CancelOrdersResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.CancelOrdersResponse")
    @WebResult(name = "CancelOrdersResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public CancelOrdersResponse2 cancelOrders(

            @WebParam(name = "cancelOrdersRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    CancelOrdersRequest cancelOrdersRequest
    );

    /**
     * Returns an account summary for the current punter.
     */
    @WebMethod(operationName = "GetAccountBalances", action = "http://www.GlobalBettingExchange.com/ExternalAPI/GetAccountBalances")
    @RequestWrapper(localName = "GetAccountBalances", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetAccountBalances")
    @ResponseWrapper(localName = "GetAccountBalancesResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetAccountBalancesResponse")
    @WebResult(name = "GetAccountBalancesResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public GetAccountBalancesResponse2 getAccountBalances(

            @WebParam(name = "getAccountBalancesRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    GetAccountBalancesRequest getAccountBalancesRequest
    );

    /**
     * Returns an account summary and details of orders placed for the current punter.
     */
    @WebMethod(operationName = "ListAccountPostings", action = "http://www.GlobalBettingExchange.com/ExternalAPI/ListAccountPostings")
    @RequestWrapper(localName = "ListAccountPostings", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListAccountPostings")
    @ResponseWrapper(localName = "ListAccountPostingsResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListAccountPostingsResponse")
    @WebResult(name = "ListAccountPostingsResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public ListAccountPostingsResponse2 listAccountPostings(

            @WebParam(name = "listAccountPostingsRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    ListAccountPostingsRequest listAccountPostingsRequest
    );

    /**
     * Returns bootstrap orders that have a sequence number greater than the sequence number specified.
     */
    @WebMethod(operationName = "ListBootstrapOrders", action = "http://www.GlobalBettingExchange.com/ExternalAPI/ListBootstrapOrders")
    @RequestWrapper(localName = "ListBootstrapOrders", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListBootstrapOrders")
    @ResponseWrapper(localName = "ListBootstrapOrdersResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListBootstrapOrdersResponse")
    @WebResult(name = "ListBootstrapOrdersResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public ListBootstrapOrdersResponse2 listBootstrapOrders(

            @WebParam(name = "listBootstrapOrdersRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    ListBootstrapOrdersRequest listBootstrapOrdersRequest
    );

    /**
     * Suspends one or more Orders.
     */
    @WebMethod(operationName = "SuspendAllOrders", action = "http://www.GlobalBettingExchange.com/ExternalAPI/SuspendAllOrders")
    @RequestWrapper(localName = "SuspendAllOrders", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.SuspendAllOrders")
    @ResponseWrapper(localName = "SuspendAllOrdersResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.SuspendAllOrdersResponse")
    @WebResult(name = "SuspendAllOrdersResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public SuspendAllOrdersResponse2 suspendAllOrders(

            @WebParam(name = "suspendAllOrdersRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    SuspendAllOrdersRequest suspendAllOrdersRequest
    );

    /**
     * List blacklist information of the current punter.
     */
    @WebMethod(operationName = "ListBlacklistInformation", action = "http://www.GlobalBettingExchange.com/ExternalAPI/ListBlacklistInformation")
    @RequestWrapper(localName = "ListBlacklistInformation", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListBlacklistInformation")
    @ResponseWrapper(localName = "ListBlacklistInformationResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListBlacklistInformationResponse")
    @WebResult(name = "ListBlacklistInformationResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public ListBlacklistInformationResponse2 listBlacklistInformation(

            @WebParam(name = "listBlacklistInformationRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    ListBlacklistInformationRequest listBlacklistInformationRequest
    );

    /**
     * Places one or more orders on the exchange.
     */
    @WebMethod(operationName = "PlaceOrdersNoReceipt", action = "http://www.GlobalBettingExchange.com/ExternalAPI/PlaceOrdersNoReceipt")
    @RequestWrapper(localName = "PlaceOrdersNoReceipt", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.PlaceOrdersNoReceipt")
    @ResponseWrapper(localName = "PlaceOrdersNoReceiptResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.PlaceOrdersNoReceiptResponse")
    @WebResult(name = "PlaceOrdersNoReceiptResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public PlaceOrdersNoReceiptResponse2 placeOrdersNoReceipt(

            @WebParam(name = "placeOrdersNoReceiptRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    PlaceOrdersNoReceiptRequest placeOrdersNoReceiptRequest
    );

    /**
     * Cancels all unmatched orders for specified markets.
     */
    @WebMethod(operationName = "CancelAllOrdersOnMarket", action = "http://www.GlobalBettingExchange.com/ExternalAPI/CancelAllOrdersOnMarket")
    @RequestWrapper(localName = "CancelAllOrdersOnMarket", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.CancelAllOrdersOnMarket")
    @ResponseWrapper(localName = "CancelAllOrdersOnMarketResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.CancelAllOrdersOnMarketResponse")
    @WebResult(name = "CancelAllOrdersOnMarketResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public CancelAllOrdersOnMarketResponse2 cancelAllOrdersOnMarket(

            @WebParam(name = "cancelAllOrdersOnMarketRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    CancelAllOrdersOnMarketRequest cancelAllOrdersOnMarketRequest
    );

    /**
     * Unsuspends one or more suspended Orders.
     */
    @WebMethod(operationName = "UnsuspendOrders", action = "http://www.GlobalBettingExchange.com/ExternalAPI/UnsuspendOrders")
    @RequestWrapper(localName = "UnsuspendOrders", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.UnsuspendOrders")
    @ResponseWrapper(localName = "UnsuspendOrdersResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.UnsuspendOrdersResponse")
    @WebResult(name = "UnsuspendOrdersResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public UnsuspendOrdersResponse2 unsuspendOrders(

            @WebParam(name = "unsuspendOrdersRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    UnsuspendOrdersRequest unsuspendOrdersRequest
    );

    /**
     * Returns a list of orders that have changed since a given sequence number.
     */
    @WebMethod(operationName = "ListOrdersChangedSince", action = "http://www.GlobalBettingExchange.com/ExternalAPI/ListOrdersChangedSince")
    @RequestWrapper(localName = "ListOrdersChangedSince", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListOrdersChangedSince")
    @ResponseWrapper(localName = "ListOrdersChangedSinceResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListOrdersChangedSinceResponse")
    @WebResult(name = "ListOrdersChangedSinceResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public ListOrdersChangedSinceResponse2 listOrdersChangedSince(

            @WebParam(name = "listOrdersChangedSinceRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    ListOrdersChangedSinceRequest listOrdersChangedSinceRequest
    );

    /**
     * Suspends all unmatched orders on a market.
     */
    @WebMethod(operationName = "SuspendAllOrdersOnMarket", action = "http://www.GlobalBettingExchange.com/ExternalAPI/SuspendAllOrdersOnMarket")
    @RequestWrapper(localName = "SuspendAllOrdersOnMarket", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.SuspendAllOrdersOnMarket")
    @ResponseWrapper(localName = "SuspendAllOrdersOnMarketResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.SuspendAllOrdersOnMarketResponse")
    @WebResult(name = "SuspendAllOrdersOnMarketResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public SuspendAllOrdersOnMarketResponse2 suspendAllOrdersOnMarket(

            @WebParam(name = "suspendAllOrdersOnMarket", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    SuspendAllOrdersOnMarketRequest suspendAllOrdersOnMarket
    );

    /**
     * Deteles HeartBeat registration.
     */
    @WebMethod(operationName = "DeregisterHeartbeat", action = "http://www.GlobalBettingExchange.com/ExternalAPI/DeregisterHeartbeat")
    @RequestWrapper(localName = "DeregisterHeartbeat", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.DeregisterHeartbeat")
    @ResponseWrapper(localName = "DeregisterHeartbeatResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.DeregisterHeartbeatResponse")
    @WebResult(name = "DeregisterHeartbeatResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public DeregisterHeartbeatResponse2 deregisterHeartbeat(

            @WebParam(name = "deregisterHeartbeatRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    DeregisterHeartbeatRequest deregisterHeartbeatRequest
    );

    /**
     * Places one or more orders on the exchange and waits for response from exchange.
     */
    @WebMethod(operationName = "PlaceOrdersWithReceipt", action = "http://www.GlobalBettingExchange.com/ExternalAPI/PlaceOrdersWithReceipt")
    @RequestWrapper(localName = "PlaceOrdersWithReceipt", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.PlaceOrdersWithReceipt")
    @ResponseWrapper(localName = "PlaceOrdersWithReceiptResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.PlaceOrdersWithReceiptResponse")
    @WebResult(name = "PlaceOrdersWithReceiptResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public PlaceOrdersWithReceiptResponse2 placeOrdersWithReceipt(

            @WebParam(name = "orders", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    PlaceOrdersWithReceiptRequest orders
    );

    /**
     * Pulse.
     */
    @WebMethod(operationName = "Pulse", action = "http://www.GlobalBettingExchange.com/ExternalAPI/Pulse")
    @RequestWrapper(localName = "Pulse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.Pulse")
    @ResponseWrapper(localName = "PulseResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.PulseResponse")
    @WebResult(name = "PulseResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public PulseResponse2 pulse(

            @WebParam(name = "pulseRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    PulseRequest pulseRequest
    );

    /**
     * Cancels all unmatched orders across all markets.
     */
    @WebMethod(operationName = "CancelAllOrders", action = "http://www.GlobalBettingExchange.com/ExternalAPI/CancelAllOrders")
    @RequestWrapper(localName = "CancelAllOrders", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.CancelAllOrders")
    @ResponseWrapper(localName = "CancelAllOrdersResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.CancelAllOrdersResponse")
    @WebResult(name = "CancelAllOrdersResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public CancelAllOrdersResponse2 cancelAllOrders(

            @WebParam(name = "cancelAllOrdersRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    CancelAllOrdersRequest cancelAllOrdersRequest
    );

    /**
     * Suspends one or more Orders.
     */
    @WebMethod(operationName = "SuspendOrders", action = "http://www.GlobalBettingExchange.com/ExternalAPI/SuspendOrders")
    @RequestWrapper(localName = "SuspendOrders", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.SuspendOrders")
    @ResponseWrapper(localName = "SuspendOrdersResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.SuspendOrdersResponse")
    @WebResult(name = "SuspendOrdersResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public SuspendOrdersResponse2 suspendOrders(

            @WebParam(name = "suspendOrdersRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    SuspendOrdersRequest suspendOrdersRequest
    );

    /**
     * Register HeartBeat.
     */
    @WebMethod(operationName = "RegisterHeartbeat", action = "http://www.GlobalBettingExchange.com/ExternalAPI/RegisterHeartbeat")
    @RequestWrapper(localName = "RegisterHeartbeat", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.RegisterHeartbeat")
    @ResponseWrapper(localName = "RegisterHeartbeatResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.RegisterHeartbeatResponse")
    @WebResult(name = "RegisterHeartbeatResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public RegisterHeartbeatResponse2 registerHeartbeat(

            @WebParam(name = "registerHeartbeatRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    RegisterHeartbeatRequest registerHeartbeatRequest
    );

    /**
     * Suspend any of your orders from being matched.
     */
    @WebMethod(operationName = "SuspendFromTrading", action = "http://www.GlobalBettingExchange.com/ExternalAPI/SuspendFromTrading")
    @RequestWrapper(localName = "SuspendFromTrading", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.SuspendFromTrading")
    @ResponseWrapper(localName = "SuspendFromTradingResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.SuspendFromTradingResponse")
    @WebResult(name = "SuspendFromTradingResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public SuspendFromTradingResponse2 suspendFromTrading(

            @WebParam(name = "suspendFromTradingRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    SuspendFromTradingRequest suspendFromTradingRequest
    );

    /**
     * Updates one or more orders on the exchange without waiting for a response.
     */
    @WebMethod(operationName = "UpdateOrdersNoReceipt", action = "http://www.GlobalBettingExchange.com/ExternalAPI/UpdateOrdersNoReceipt")
    @RequestWrapper(localName = "UpdateOrdersNoReceipt", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.UpdateOrdersNoReceipt")
    @ResponseWrapper(localName = "UpdateOrdersNoReceiptResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.UpdateOrdersNoReceiptResponse")
    @WebResult(name = "UpdateOrdersNoReceiptResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public UpdateOrdersNoReceiptResponse2 updateOrdersNoReceipt(

            @WebParam(name = "updateOrdersNoReceiptRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    UpdateOrdersNoReceiptRequest updateOrdersNoReceiptRequest
    );

    /**
     * Change HeartBeat registration.
     */
    @WebMethod(operationName = "ChangeHeartbeatRegistration", action = "http://www.GlobalBettingExchange.com/ExternalAPI/ChangeHeartbeatRegistration")
    @RequestWrapper(localName = "ChangeHeartbeatRegistration", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ChangeHeartbeatRegistration")
    @ResponseWrapper(localName = "ChangeHeartbeatRegistrationResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ChangeHeartbeatRegistrationResponse")
    @WebResult(name = "ChangeHeartbeatRegistrationResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public ChangeHeartbeatRegistrationResponse2 changeHeartbeatRegistration(

            @WebParam(name = "changeHeartbeatRegistrationRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    ChangeHeartbeatRegistrationRequest changeHeartbeatRegistrationRequest
    );

    /**
     * Returns an account summary and details of orders placed for the current punter.
     */
    @WebMethod(operationName = "ListAccountPostingsById", action = "http://www.GlobalBettingExchange.com/ExternalAPI/ListAccountPostingsById")
    @RequestWrapper(localName = "ListAccountPostingsById", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListAccountPostingsById")
    @ResponseWrapper(localName = "ListAccountPostingsByIdResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ListAccountPostingsByIdResponse")
    @WebResult(name = "ListAccountPostingsByIdResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public ListAccountPostingsByIdResponse2 listAccountPostingsById(

            @WebParam(name = "listAccountPostingsByIdRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    ListAccountPostingsByIdRequest listAccountPostingsByIdRequest
    );

    /**
     * Gets detailed information about an order.
     */
    @WebMethod(operationName = "GetOrderDetails", action = "http://www.GlobalBettingExchange.com/ExternalAPI/GetOrderDetails")
    @RequestWrapper(localName = "GetOrderDetails", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetOrderDetails")
    @ResponseWrapper(localName = "GetOrderDetailsResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.GetOrderDetailsResponse")
    @WebResult(name = "GetOrderDetailsResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public GetOrderDetailsResponse2 getOrderDetails(

            @WebParam(name = "getOrderDetailsRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    GetOrderDetailsRequest getOrderDetailsRequest
    );

    /**
     * Change password on the current account.
     */
    @WebMethod(operationName = "ChangePassword", action = "http://www.GlobalBettingExchange.com/ExternalAPI/ChangePassword")
    @RequestWrapper(localName = "ChangePassword", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ChangePassword")
    @ResponseWrapper(localName = "ChangePasswordResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.ChangePasswordResponse")
    @WebResult(name = "ChangePasswordResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public ChangePasswordResponse2 changePassword(

            @WebParam(name = "changePasswordRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    ChangePasswordRequest changePasswordRequest
    );

    /**
     * Unsuspend yourself from being suspending from trading.
     */
    @WebMethod(operationName = "UnsuspendFromTrading", action = "http://www.GlobalBettingExchange.com/ExternalAPI/UnsuspendFromTrading")
    @RequestWrapper(localName = "UnsuspendFromTrading", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.UnsuspendFromTrading")
    @ResponseWrapper(localName = "UnsuspendFromTradingResponse", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/", className = "com.globalbettingexchange.externalapi.UnsuspendFromTradingResponse")
    @WebResult(name = "UnsuspendFromTradingResult", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
    public UnsuspendFromTradingResponse2 unsuspendFromTrading(

            @WebParam(name = "unsuspendFromTradingRequest", targetNamespace = "http://www.GlobalBettingExchange.com/ExternalAPI/")
                    UnsuspendFromTradingRequest unsuspendFromTradingRequest
    );
}
